-- Seed / upsert catalogue depuis menuData + homeProductCarousel (généré)
INSERT INTO public.products (
  slug,
  name,
  category,
  price,
  calories,
  protein,
  description,
  ingredients,
  benefits,
  pitch,
  icon_emoji,
  image_url,
  active,
  carousel_sort,
  carousel_badge,
  badges
) VALUES
(
  'glow-my-skin',
  'GLOW MY SKIN',
  'wellness',
  10,
  30,
  NULL,
  'Le cocktail beauté par excellence',
  ARRAY['Hibiscus', 'Collagène', 'Fraise', 'Citron']::text[],
  ARRAY['Articulation', 'Circulation sanguine', 'Peau', 'Ongles et cheveux']::text[],
  'Le cocktail beauté par excellence',
  '✨',
  '/home-showcase-glow-my-skin.png',
  true,
  8,
  NULL,
  ARRAY[]::text[]
),
(
  'detox-my-body',
  'DETOX MY BODY',
  'wellness',
  10,
  30,
  NULL,
  'Le nettoyage interne frais et léger',
  ARRAY['Thé vert cardamome', 'Verveine', 'Menthe', 'Yuzu', 'Aloé Vera']::text[],
  ARRAY['Brûle graisse', 'Confort digestif', 'Effet drainant']::text[],
  'Le nettoyage interne frais et léger',
  '🌿',
  NULL,
  true,
  9,
  NULL,
  ARRAY[]::text[]
),
(
  'immune-paradis',
  'IMMUNE PARADIS',
  'wellness',
  10,
  35,
  NULL,
  'Contribue au fonctionnement du système immunitaire',
  ARRAY['Baies sauvages', 'Passion', 'Rose', 'Aloe vera']::text[],
  ARRAY['Système immunitaire', 'Antioxydant', 'Douceur', 'Vitalité']::text[],
  'Contribue au fonctionnement du système immunitaire',
  '🌸',
  NULL,
  true,
  NULL,
  NULL,
  ARRAY[]::text[]
),
(
  'spicy-mango',
  'SPICY MANGO',
  'energie',
  10,
  50,
  NULL,
  'Le boost tropical et puissant',
  ARRAY['Mangue épicée', 'Açaï', 'Créatine', 'Hibiscus', 'Orange', 'Électrolytes']::text[],
  ARRAY['Énergie', 'Endurance', 'Puissance', 'Hydratation', 'Anti-crampe']::text[],
  'Le boost tropical et puissant',
  '🔥',
  NULL,
  true,
  NULL,
  NULL,
  ARRAY[]::text[]
),
(
  'blue-lagoon',
  'BLUE LAGOON',
  'energie',
  10,
  50,
  NULL,
  'L''électrochoc frais pour se réveiller',
  ARRAY['Créatine', 'Yuzu', 'Açaï', 'Citron', 'Curaçao', 'Menthe', 'Caféine de Guarana', 'Biotine', 'Taurine']::text[],
  ARRAY['Énergie rapide', 'Endurance', 'Puissance', 'Hydratation', 'Anti-crampe']::text[],
  'L''électrochoc frais pour se réveiller',
  '💙',
  '/home-showcase-blue-lagoon.png',
  true,
  2,
  NULL,
  ARRAY[]::text[]
),
(
  'coco-boost',
  'COCO BOOST',
  'energie',
  10,
  25,
  NULL,
  'Hydratation naturelle & récupération',
  ARRAY['Eau de coco', 'Aloé', 'Electrolytes', 'Curaçao']::text[],
  ARRAY['Hydratation naturelle', 'Récupération', 'Endurance', 'Équilibre électrolytique', 'Anti-crampes']::text[],
  'Hydratation naturelle, récupération, endurance, équilibre électrolytique, anti-crampes',
  '🥥',
  NULL,
  true,
  NULL,
  NULL,
  ARRAY[]::text[]
),
(
  'pink-dragon',
  'PINK DRAGON',
  'shakes',
  14,
  230,
  21,
  'Fruité & Beauté',
  ARRAY['Fruit du dragon', 'Collagène', 'Fraise']::text[],
  ARRAY['Récupération', 'Beauté', '21g protéines', '25 vitamines & minéraux']::text[],
  'Fruité & Beauté',
  '🐉',
  '/home-showcase-pink-dragon-shake.png',
  true,
  1,
  'nouveaute',
  ARRAY['vegan', 'glutenfree', 'vitamins']::text[]
),
(
  'cookie-cream',
  'COOKIE CREAM',
  'shakes',
  14,
  220,
  18,
  'Gourmandise pure',
  ARRAY['Cookies', 'Caramel', 'Chocolat']::text[],
  ARRAY['Récupération', 'Gourmand', '18g protéines', '25 vitamines & minéraux']::text[],
  'Gourmandise pure',
  '🍪',
  NULL,
  true,
  3,
  'coup-de-coeur',
  ARRAY['vegan', 'glutenfree', 'vitamins']::text[]
),
(
  'choco-prot',
  'CHOCO PROT',
  'shakes',
  14,
  250,
  20,
  'Le classique efficace',
  ARRAY['Cacao', 'Vanille']::text[],
  ARRAY['Récupération', 'Classique', '20g protéines', '25 vitamines & minéraux']::text[],
  'Le classique efficace',
  '🍫',
  NULL,
  true,
  4,
  NULL,
  ARRAY['vegan', 'glutenfree', 'vitamins']::text[]
),
(
  'iced-caramel-latte',
  'CARAMEL GLACÉ',
  'shakes',
  14,
  220,
  18,
  'Le coup de fouet gourmand',
  ARRAY['Vanille', 'Caramel', 'Café']::text[],
  ARRAY['Récupération', 'Énergie', '18g protéines', '25 vitamines & minéraux']::text[],
  'Le coup de fouet gourmand',
  '☕',
  NULL,
  true,
  5,
  NULL,
  ARRAY['vegan', 'glutenfree', 'vitamins']::text[]
),
(
  'tiramisu-creamy',
  'TIRAMISU GOURMAND',
  'shakes',
  14,
  220,
  18,
  'Dessert liquide',
  ARRAY['Spéculos', 'Café', 'Vanille', 'Poudre de cacao']::text[],
  ARRAY['Récupération', 'Gourmand', '18g protéines', '25 vitamines & minéraux']::text[],
  'Dessert liquide',
  '🍰',
  NULL,
  true,
  6,
  NULL,
  ARRAY['vegan', 'glutenfree', 'vitamins']::text[]
),
(
  'glam-matcha',
  'GLAM MATCHA',
  'shakes',
  14,
  220,
  18,
  'L''option zen & fruitée',
  ARRAY['Matcha', 'Vanille', 'Framboise', 'Lait Végétal']::text[],
  ARRAY['Récupération', 'Antioxydants', '18g protéines', '25 vitamines & minéraux']::text[],
  'L''option zen & fruitée',
  '🍵',
  NULL,
  true,
  7,
  NULL,
  ARRAY['vegan', 'glutenfree', 'vitamins']::text[]
),
(
  'espresso',
  'ESPRESSO',
  'coffee',
  2.5,
  5,
  NULL,
  'Court et intense',
  ARRAY['Café arabica']::text[],
  ARRAY['Énergie', 'Concentration']::text[],
  'Le classique italien',
  '☕',
  NULL,
  true,
  NULL,
  NULL,
  ARRAY[]::text[]
),
(
  'cafe-long',
  'CAFÉ LONG',
  'coffee',
  4,
  10,
  NULL,
  'Allongé et doux',
  ARRAY['Café arabica', 'Eau']::text[],
  ARRAY['Énergie douce', 'Hydratation']::text[],
  'Pour prendre son temps',
  '☕',
  NULL,
  true,
  NULL,
  NULL,
  ARRAY[]::text[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  calories = EXCLUDED.calories,
  protein = EXCLUDED.protein,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  benefits = EXCLUDED.benefits,
  pitch = EXCLUDED.pitch,
  icon_emoji = EXCLUDED.icon_emoji,
  image_url = COALESCE(EXCLUDED.image_url, public.products.image_url),
  active = EXCLUDED.active,
  carousel_sort = EXCLUDED.carousel_sort,
  carousel_badge = EXCLUDED.carousel_badge,
  badges = EXCLUDED.badges;

